/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RateConfigRouteImport } from './routes/rate-config'
import { Route as RateCellsRouteImport } from './routes/rate-cells'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PaymentLedgerRouteImport } from './routes/payment-ledger'
import { Route as MissingSubmissionsRouteImport } from './routes/missing-submissions'
import { Route as EnrollmentWindowsRouteImport } from './routes/enrollment-windows'
import { Route as EnrollmentResponsesRouteImport } from './routes/enrollment-responses'
import { Route as EnrolleeBalanceRouteImport } from './routes/enrollee-balance'
import { Route as CommissionRouteImport } from './routes/commission'
import { Route as CarriersRouteImport } from './routes/carriers'
import { Route as BillingGroupsRouteImport } from './routes/billing-groups'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AffiliatesRouteImport } from './routes/affiliates'
import { Route as AccountAdjustmentsRouteImport } from './routes/account-adjustments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as OrganizationsIndexRouteImport } from './routes/organizations.index'
import { Route as IndividualsIndexRouteImport } from './routes/individuals.index'
import { Route as ReportsSlugRouteImport } from './routes/reports.$slug'
import { Route as OrganizationsIdRouteImport } from './routes/organizations.$id'
import { Route as IndividualsIdRouteImport } from './routes/individuals.$id'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RateConfigRoute = RateConfigRouteImport.update({
  id: '/rate-config',
  path: '/rate-config',
  getParentRoute: () => rootRouteImport,
} as any)
const RateCellsRoute = RateCellsRouteImport.update({
  id: '/rate-cells',
  path: '/rate-cells',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentLedgerRoute = PaymentLedgerRouteImport.update({
  id: '/payment-ledger',
  path: '/payment-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const MissingSubmissionsRoute = MissingSubmissionsRouteImport.update({
  id: '/missing-submissions',
  path: '/missing-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentWindowsRoute = EnrollmentWindowsRouteImport.update({
  id: '/enrollment-windows',
  path: '/enrollment-windows',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrollmentResponsesRoute = EnrollmentResponsesRouteImport.update({
  id: '/enrollment-responses',
  path: '/enrollment-responses',
  getParentRoute: () => rootRouteImport,
} as any)
const EnrolleeBalanceRoute = EnrolleeBalanceRouteImport.update({
  id: '/enrollee-balance',
  path: '/enrollee-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionRoute = CommissionRouteImport.update({
  id: '/commission',
  path: '/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const CarriersRoute = CarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingGroupsRoute = BillingGroupsRouteImport.update({
  id: '/billing-groups',
  path: '/billing-groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliatesRoute = AffiliatesRouteImport.update({
  id: '/affiliates',
  path: '/affiliates',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAdjustmentsRoute = AccountAdjustmentsRouteImport.update({
  id: '/account-adjustments',
  path: '/account-adjustments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const OrganizationsIndexRoute = OrganizationsIndexRouteImport.update({
  id: '/organizations/',
  path: '/organizations/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIndexRoute = IndividualsIndexRouteImport.update({
  id: '/individuals/',
  path: '/individuals/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSlugRoute = ReportsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ReportsRoute,
} as any)
const OrganizationsIdRoute = OrganizationsIdRouteImport.update({
  id: '/organizations/$id',
  path: '/organizations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIdRoute = IndividualsIdRouteImport.update({
  id: '/individuals/$id',
  path: '/individuals/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-adjustments': typeof AccountAdjustmentsRoute
  '/affiliates': typeof AffiliatesRoute
  '/audit': typeof AuditRoute
  '/billing-groups': typeof BillingGroupsRoute
  '/carriers': typeof CarriersRoute
  '/commission': typeof CommissionRoute
  '/enrollee-balance': typeof EnrolleeBalanceRoute
  '/enrollment-responses': typeof EnrollmentResponsesRoute
  '/enrollment-windows': typeof EnrollmentWindowsRoute
  '/missing-submissions': typeof MissingSubmissionsRoute
  '/payment-ledger': typeof PaymentLedgerRoute
  '/policies': typeof PoliciesRoute
  '/rate-cells': typeof RateCellsRoute
  '/rate-config': typeof RateConfigRoute
  '/reports': typeof ReportsRouteWithChildren
  '/tokens': typeof TokensRoute
  '/individuals/$id': typeof IndividualsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/individuals/': typeof IndividualsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-adjustments': typeof AccountAdjustmentsRoute
  '/affiliates': typeof AffiliatesRoute
  '/audit': typeof AuditRoute
  '/billing-groups': typeof BillingGroupsRoute
  '/carriers': typeof CarriersRoute
  '/commission': typeof CommissionRoute
  '/enrollee-balance': typeof EnrolleeBalanceRoute
  '/enrollment-responses': typeof EnrollmentResponsesRoute
  '/enrollment-windows': typeof EnrollmentWindowsRoute
  '/missing-submissions': typeof MissingSubmissionsRoute
  '/payment-ledger': typeof PaymentLedgerRoute
  '/policies': typeof PoliciesRoute
  '/rate-cells': typeof RateCellsRoute
  '/rate-config': typeof RateConfigRoute
  '/tokens': typeof TokensRoute
  '/individuals/$id': typeof IndividualsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/individuals': typeof IndividualsIndexRoute
  '/organizations': typeof OrganizationsIndexRoute
  '/reports': typeof ReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-adjustments': typeof AccountAdjustmentsRoute
  '/affiliates': typeof AffiliatesRoute
  '/audit': typeof AuditRoute
  '/billing-groups': typeof BillingGroupsRoute
  '/carriers': typeof CarriersRoute
  '/commission': typeof CommissionRoute
  '/enrollee-balance': typeof EnrolleeBalanceRoute
  '/enrollment-responses': typeof EnrollmentResponsesRoute
  '/enrollment-windows': typeof EnrollmentWindowsRoute
  '/missing-submissions': typeof MissingSubmissionsRoute
  '/payment-ledger': typeof PaymentLedgerRoute
  '/policies': typeof PoliciesRoute
  '/rate-cells': typeof RateCellsRoute
  '/rate-config': typeof RateConfigRoute
  '/reports': typeof ReportsRouteWithChildren
  '/tokens': typeof TokensRoute
  '/individuals/$id': typeof IndividualsIdRoute
  '/organizations/$id': typeof OrganizationsIdRoute
  '/reports/$slug': typeof ReportsSlugRoute
  '/individuals/': typeof IndividualsIndexRoute
  '/organizations/': typeof OrganizationsIndexRoute
  '/reports/': typeof ReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-adjustments'
    | '/affiliates'
    | '/audit'
    | '/billing-groups'
    | '/carriers'
    | '/commission'
    | '/enrollee-balance'
    | '/enrollment-responses'
    | '/enrollment-windows'
    | '/missing-submissions'
    | '/payment-ledger'
    | '/policies'
    | '/rate-cells'
    | '/rate-config'
    | '/reports'
    | '/tokens'
    | '/individuals/$id'
    | '/organizations/$id'
    | '/reports/$slug'
    | '/individuals/'
    | '/organizations/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-adjustments'
    | '/affiliates'
    | '/audit'
    | '/billing-groups'
    | '/carriers'
    | '/commission'
    | '/enrollee-balance'
    | '/enrollment-responses'
    | '/enrollment-windows'
    | '/missing-submissions'
    | '/payment-ledger'
    | '/policies'
    | '/rate-cells'
    | '/rate-config'
    | '/tokens'
    | '/individuals/$id'
    | '/organizations/$id'
    | '/reports/$slug'
    | '/individuals'
    | '/organizations'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/account-adjustments'
    | '/affiliates'
    | '/audit'
    | '/billing-groups'
    | '/carriers'
    | '/commission'
    | '/enrollee-balance'
    | '/enrollment-responses'
    | '/enrollment-windows'
    | '/missing-submissions'
    | '/payment-ledger'
    | '/policies'
    | '/rate-cells'
    | '/rate-config'
    | '/reports'
    | '/tokens'
    | '/individuals/$id'
    | '/organizations/$id'
    | '/reports/$slug'
    | '/individuals/'
    | '/organizations/'
    | '/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountAdjustmentsRoute: typeof AccountAdjustmentsRoute
  AffiliatesRoute: typeof AffiliatesRoute
  AuditRoute: typeof AuditRoute
  BillingGroupsRoute: typeof BillingGroupsRoute
  CarriersRoute: typeof CarriersRoute
  CommissionRoute: typeof CommissionRoute
  EnrolleeBalanceRoute: typeof EnrolleeBalanceRoute
  EnrollmentResponsesRoute: typeof EnrollmentResponsesRoute
  EnrollmentWindowsRoute: typeof EnrollmentWindowsRoute
  MissingSubmissionsRoute: typeof MissingSubmissionsRoute
  PaymentLedgerRoute: typeof PaymentLedgerRoute
  PoliciesRoute: typeof PoliciesRoute
  RateCellsRoute: typeof RateCellsRoute
  RateConfigRoute: typeof RateConfigRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  TokensRoute: typeof TokensRoute
  IndividualsIdRoute: typeof IndividualsIdRoute
  OrganizationsIdRoute: typeof OrganizationsIdRoute
  IndividualsIndexRoute: typeof IndividualsIndexRoute
  OrganizationsIndexRoute: typeof OrganizationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-config': {
      id: '/rate-config'
      path: '/rate-config'
      fullPath: '/rate-config'
      preLoaderRoute: typeof RateConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate-cells': {
      id: '/rate-cells'
      path: '/rate-cells'
      fullPath: '/rate-cells'
      preLoaderRoute: typeof RateCellsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-ledger': {
      id: '/payment-ledger'
      path: '/payment-ledger'
      fullPath: '/payment-ledger'
      preLoaderRoute: typeof PaymentLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missing-submissions': {
      id: '/missing-submissions'
      path: '/missing-submissions'
      fullPath: '/missing-submissions'
      preLoaderRoute: typeof MissingSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment-windows': {
      id: '/enrollment-windows'
      path: '/enrollment-windows'
      fullPath: '/enrollment-windows'
      preLoaderRoute: typeof EnrollmentWindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollment-responses': {
      id: '/enrollment-responses'
      path: '/enrollment-responses'
      fullPath: '/enrollment-responses'
      preLoaderRoute: typeof EnrollmentResponsesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enrollee-balance': {
      id: '/enrollee-balance'
      path: '/enrollee-balance'
      fullPath: '/enrollee-balance'
      preLoaderRoute: typeof EnrolleeBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission': {
      id: '/commission'
      path: '/commission'
      fullPath: '/commission'
      preLoaderRoute: typeof CommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carriers': {
      id: '/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof CarriersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing-groups': {
      id: '/billing-groups'
      path: '/billing-groups'
      fullPath: '/billing-groups'
      preLoaderRoute: typeof BillingGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliates': {
      id: '/affiliates'
      path: '/affiliates'
      fullPath: '/affiliates'
      preLoaderRoute: typeof AffiliatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-adjustments': {
      id: '/account-adjustments'
      path: '/account-adjustments'
      fullPath: '/account-adjustments'
      preLoaderRoute: typeof AccountAdjustmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/organizations/': {
      id: '/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof OrganizationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/': {
      id: '/individuals/'
      path: '/individuals'
      fullPath: '/individuals/'
      preLoaderRoute: typeof IndividualsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$slug': {
      id: '/reports/$slug'
      path: '/$slug'
      fullPath: '/reports/$slug'
      preLoaderRoute: typeof ReportsSlugRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/organizations/$id': {
      id: '/organizations/$id'
      path: '/organizations/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof OrganizationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/$id': {
      id: '/individuals/$id'
      path: '/individuals/$id'
      fullPath: '/individuals/$id'
      preLoaderRoute: typeof IndividualsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ReportsRouteChildren {
  ReportsSlugRoute: typeof ReportsSlugRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsSlugRoute: ReportsSlugRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountAdjustmentsRoute: AccountAdjustmentsRoute,
  AffiliatesRoute: AffiliatesRoute,
  AuditRoute: AuditRoute,
  BillingGroupsRoute: BillingGroupsRoute,
  CarriersRoute: CarriersRoute,
  CommissionRoute: CommissionRoute,
  EnrolleeBalanceRoute: EnrolleeBalanceRoute,
  EnrollmentResponsesRoute: EnrollmentResponsesRoute,
  EnrollmentWindowsRoute: EnrollmentWindowsRoute,
  MissingSubmissionsRoute: MissingSubmissionsRoute,
  PaymentLedgerRoute: PaymentLedgerRoute,
  PoliciesRoute: PoliciesRoute,
  RateCellsRoute: RateCellsRoute,
  RateConfigRoute: RateConfigRoute,
  ReportsRoute: ReportsRouteWithChildren,
  TokensRoute: TokensRoute,
  IndividualsIdRoute: IndividualsIdRoute,
  OrganizationsIdRoute: OrganizationsIdRoute,
  IndividualsIndexRoute: IndividualsIndexRoute,
  OrganizationsIndexRoute: OrganizationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
